import { LegalPageLayout } from '../ui/LegalPageLayout.js';
import { LegalConfig } from '../../config/legalConfig.js';

export const renderTermsOfService = (container) => {
    const content = `
        <h2>1. Acceptance of Terms</h2>
        <p>By accessing and using <strong>${LegalConfig.siteName}</strong> ("the Website", "we", "us", or "our"), you agree to comply with and be bound by these Terms of Service. If you do not agree with any part of these terms, you must not use our website or tools.</p>

        <h2>2. Description of Service</h2>
        <p>${LegalConfig.siteName} provides a suite of free, browser-based online tools, calculators, and educational resources ("the Services"). The tools process data locally on your device using client-side JavaScript technologies.</p>

        <h2>3. Permitted Use</h2>
        <p>You are granted a non-exclusive, non-transferable, revocable license to access and use the Services strictly in accordance with these terms. You agree to use the Services only for lawful purposes and in a way that does not infringe the rights of, restrict, or inhibit anyone else's use and enjoyment of the Website.</p>

        <h2>4. Prohibited Use</h2>
        <p>You agree not to:</p>
        <ul>
            <li>Use the Website or its tools for any illegal or unauthorized purpose.</li>
            <li>Attempt to reverse-engineer, decompile, or hack the Website's underlying code or infrastructure.</li>
            <li>Use automated bots, scrapers, or crawlers to access the Website in a manner that strains our hosting resources.</li>
            <li>Use the Website to distribute malware, viruses, or harmful code.</li>
        </ul>

        <h2>5. User Responsibility and File Processing</h2>
        <p>Because our tools operate client-side in your browser, you maintain full control and responsibility over the files and data you process. We do not store backups of your processed files. It is your responsibility to ensure you have original copies of any files before processing them with our tools.</p>

        <h2>6. Accuracy of Tools and Calculators</h2>
        <p>While we strive for accuracy, the results generated by our calculators, converters, and formatting tools are provided for informational and educational purposes only. We do not guarantee the absolute correctness, completeness, or reliability of any output. You should independently verify any critical calculations, especially those related to finances, taxes, or academic grades.</p>

        <h2>7. Intellectual Property</h2>
        <p>The design, layout, source code, text, and graphics of the Website are owned by or licensed to us and are protected by copyright and intellectual property laws. You may not reproduce, distribute, or create derivative works from our content without explicit permission.</p>

        <h2>8. Third-Party Links and Advertising</h2>
        <p>The Website may contain links to third-party websites or services that are not owned or controlled by us. Furthermore, we may display advertisements provided by third-party networks (e.g., Google AdSense). We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party websites or services.</p>

        <h2>9. No Warranty</h2>
        <p>THE SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. WE EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE.</p>

        <h2>10. Limitation of Liability</h2>
        <p>IN NO EVENT SHALL ${LegalConfig.siteName}, ITS CREATORS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (A) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICES; (B) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICES; OR (C) ANY UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT.</p>

        <h2>11. Modifications to the Service and Terms</h2>
        <p>We reserve the right to modify or discontinue, temporarily or permanently, the Services (or any part thereof) with or without notice. We may also revise these Terms of Service at any time. By continuing to access or use our Services after those revisions become effective, you agree to be bound by the revised terms.</p>

        <h2>12. Governing Law</h2>
        <p>These Terms shall be governed and construed in accordance with the laws of ${LegalConfig.governingLaw}, without regard to its conflict of law provisions.</p>

        <h2>13. Contact Information</h2>
        <p>If you have any questions about these Terms, please contact us at:</p>
        <p><strong>Email:</strong> <a href="mailto:${LegalConfig.contactEmail}">${LegalConfig.contactEmail}</a></p>
    `;

    container.innerHTML = LegalPageLayout({
        title: 'Terms of Service',
        seoTitle: `Terms of Service - ${LegalConfig.siteName}`,
        seoDescription: 'Read the Terms of Service for Student Utility Hub. Learn about permitted usage, limitations of liability, and service agreements.',
        slug: 'terms-of-service',
        content
    });
};
